dist: focal
language: python

python:
  - '3.7'
  - '3.8'
  - '3.9'

script:
  - make build
  - make test

deploy:
  provider: pypi
  user: lifeofguenter
  password:
    secure: th6RJEr5sMwRM0vucs/JVlHlNwBoyheeUmDar4wUPJiZ5L49RGG6vav3TgwOHZGrujPHIA08tbzWYLBdCUAHp5VFY0SYdn8uj5Ym8ECMvIimr8N/pqy1G4sAvl7UelGZ3Z09gWRE513hq1Ny93JqHrpF1YzKPkTeRjOaLaFui1HkvuQVy3Mf43s0Li7iEKx/8lbK5qD/Hxgd4ZiN2fWUTD5vEmzpo6m2+G3qrsU2nQqav0M8Nam+h/xDZ3JupQQ/S4CnWdznsjIBmHf0qhygjwmTzruIM8nWRtXo5kHMn4ESazPJC2aqaz6rFRTYxqO5NwdZv3DaTFeTVONyjTkEXD5QDO0doynqNiIfmyraMwJhmwjJwNkplbgbVgAFEADEtGVM/JnBBpEHyA+Ti80I7JwIHVVn23vWMWc595CMYPwjUK07DyRwW+QdMafH9yyfekNZbuD47s5bi2ZQRICOPKJsv1Bih93foMii+2x23HJYYLkiONxwU6/gKy/XW7zg+mLUFRwuHogsYt7K+BPaIh1Pa3BubFRNzJ/T8wpsYiUVWiALZgSxG45PFm7C+LMSAlUxE1aVAHm+ijxCSRy3cR3Aagnvhi0t6lNHoafUVcJj50xmD6pkzNP5CnbX/Fbjn9doLU7hRs6snuMRIZ3xrlPGVTAe6ZeahcFGtcmIhBE=
  on:
    tags: true
    condition: $MY_ENV = super_awesome
